language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
# command to install dependencies
install:
  - pip install . --use-mirrors
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
script: nosetests #--with-coverage --cover-package flask_sillywalk
